name: Build and Release MiniAwake

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup Visual Studio environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Build Release x64
        run: msbuild MiniAwake.sln /p:Configuration=Release /p:Platform=x64

      - name: Package zip
        run: |
          mkdir output
          copy x64\Release\MiniAwake.exe output\MiniAwake-${{ github.ref_name }}-x64.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            output/MiniAwake-${{ github.ref_name }}-x64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
